server:
  port: 8881

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TienNLN/spring-cloud-config-server-demo.git
          clone-on-start: true

  security:
    user:
      name: admin
      password: 1234
