server:
  port: 8881

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://localhost/config-repo
          clone-on-start: true

  security:
    user:
      name: admin
      password: 123
