name: config

user:
  role: sit

database:
  url: sit_database
  username: database_admin_sit
  password: database_admin_sit

redis:
  url: redis_sit
  username: redis_admin_sit_changed
  password: redis_admin_sit_changed

spring:
  profiles:
    active: sit